from re import S
import pygame
from pygame.locals import *
from pygame import mixer

pygame.init()
pygame.mixer.init()


# Sounds

FORZA_ROMA = pygame.mixer.Sound("sounds/forza_roma.wav")
OOF = pygame.mixer.Sound("sounds/oof.wav")
DIRECTIONAL_SELECTION = pygame.mixer.Sound("sounds/directional_selection.wav")
CONFIRM = pygame.mixer.Sound("sounds/confirm.wav")
PULSE = pygame.mixer.Sound("sounds/pulse.wav")
MULTIPLE_HI_HIT = pygame.mixer.Sound("sounds/multiple_hi_hit.wav")
MULTIPLE_LOW_HIT = pygame.mixer.Sound("sounds/multiple_low_hit.wav")
MULTIPLE_HIT = pygame.mixer.Sound("sounds/multiple_hit.wav")
HITTED = pygame.mixer.Sound("sounds/hitted.wav")
TORNADO  = pygame.mixer.Sound("sounds/tornado.wav")
THUNDER_STRIKE = pygame.mixer.Sound("sounds/thunder_strike.wav")
CHARGING = pygame.mixer.Sound("sounds/charging.wav")
HIT_SKILL = pygame.mixer.Sound("sounds/hit_skill.wav")
HIT_SKILL_1 = pygame.mixer.Sound("sounds/hit_skill_1.wav")
STATS_BOOST = pygame.mixer.Sound("sounds/stats_boost.wav")
STATS_DEBUFF = pygame.mixer.Sound("sounds/stats_debuff.wav")
RECOVER = pygame.mixer.Sound("sounds/recover.wav")
DEATH = pygame.mixer.Sound("sounds/death.wav")
BONK = pygame.mixer.Sound("sounds/bonk.wav")
AIMING = pygame.mixer.Sound("sounds/aiming.wav")
SNIPER = pygame.mixer.Sound("sounds/sniper.wav")
CRACKED_SKULL = pygame.mixer.Sound("sounds/cracked_skull.wav")
BENEVENTO = pygame.mixer.Sound("sounds/benevento.wav")
DITINO = pygame.mixer.Sound("sounds/ditino.wav")
PROVOCAZIONE = pygame.mixer.Sound("sounds/provocazione.wav")
FALLING = pygame.mixer.Sound("sounds/falling.wav")
MALEVENTO = pygame.mixer.Sound("sounds/malevento.wav")
EXPLOSIVE_COLLISION = pygame.mixer.Sound("sounds/explosive_collision.wav")
HELP_REQUEST = pygame.mixer.Sound("sounds/help_request.wav")
FIRE = pygame.mixer.Sound("sounds/fire.wav")
FRUSH_FRUSH = pygame.mixer.Sound("sounds/frush_frusha.wav")
CHANGE_PAGE = pygame.mixer.Sound("sounds/change_page.wav")
CRYING = pygame.mixer.Sound("sounds/crying.wav")
BEEP_LEFT = pygame.mixer.Sound("sounds/beep_left.wav")
BEEP_DOWN = pygame.mixer.Sound("sounds/beep_low.wav")
BEEP_UP = pygame.mixer.Sound("sounds/beep_up.wav")
BEEP_RIGHT = pygame.mixer.Sound("sounds/beep_right.wav")
EATING = pygame.mixer.Sound("sounds/eating.wav")
ANGELIC_CHORES = pygame.mixer.Sound("sounds/angelic_chores.wav")
SELECTING_BOSS = pygame.mixer.Sound("sounds/selecting_boss.wav")
ZZAAP_CHARGE = pygame.mixer.Sound("sounds/zzaap_charge.wav")
ZZAAP_END = pygame.mixer.Sound("sounds/zzaap_end.wav")
GAIN_HEALTH = pygame.mixer.Sound("sounds/gain_healtha.wav")
TRANSITION = pygame.mixer.Sound("sounds/transition.wav")
EXPLOSION = pygame.mixer.Sound("sounds/explosion.wav")
CHEERS = pygame.mixer.Sound("sounds/cheers.wav")
LITTLE_BREEZE = pygame.mixer.Sound("sounds/little_breeze.wav")
TIME_CHANGE = pygame.mixer.Sound("sounds/time_change.wav")
CUT = pygame.mixer.Sound("sounds/cut.wav")
DEEP_HIT = pygame.mixer.Sound("sounds/deep_hit.wav")
LOW_VOICE = pygame.mixer.Sound("sounds/low_voice.wav")
LOUD_VOICE1 = pygame.mixer.Sound("sounds/loud_voice1.wav")
LOUD_VOICE2 = pygame.mixer.Sound("sounds/loud_voice2.wav")
LOUD_VOICE3 = pygame.mixer.Sound("sounds/loud_voice3.wav")
FAST_HIT = pygame.mixer.Sound("sounds/fast_hit.wav")
BLESSED = pygame.mixer.Sound("sounds/blessed.wav")